name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Execute every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Update Data Job
    runs-on: ubuntu-latest
    steps:
      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Vasallo94
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: GitHub Pages Deployment
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
